### ISSUE TITLE
Generated tokens are not RFC compatible

### ISSUE THREAD

**Issue by lcobucci** [RobDWaller/ReallySimpleJWT#1]
> A JWT is represented as a sequence of URL-safe parts separated by
period ('.') characters.  Each part contains a base64url-encoded value.

[RFC 7519 - section 3](https://tools.ietf.org/html/rfc7519#section-3). The lib is using Base64 encoding and not Base64URL.

Maybe [lcobucci/jose-parsing](https://github.com/lcobucci/jose-parsing/blob/master/src/Parser.php) can help you 😉

**Comment by lcobucci** [comment]
Solving that you can also remove the [URL Encoding](https://github.com/RobDWaller/ReallySimpleJWT#url-encoding) section from readme.

**Comment by RobDWaller** [comment]
Yes, I thought I might be missing something here in the concept of JWT but couldn't find any docs on it.

I will take a look and tidy it up.

**Comment by RobDWaller** [comment]
I think I've corrected this, it needs a tidy up of course. Also I've seen what you mean in your code, much more efficient than what I've just done.

I've checked the tokens on JWT.io but would love your confirmation it is correct. Then I'll tidy it up.

**Comment by lcobucci** [comment]
It's not 100% yet 😄 

You're not [adding the padding back](https://github.com/lcobucci/jose-parsing/blob/c01b594860ca5785b17b3ba2c86dd085b6f7cde2/src/Parser.php#L69) if needed.

BTW you can simplify things by passing arrays to [`str_replace()`](http://php.net/manual/en/function.str-replace.php).

**Comment by RobDWaller** [comment]
I did not know that about str_replace(), I should read the docs more thoroughly.

This is really great, thank you so much, I am in your debt.

**Comment by RobDWaller** [comment]
I think I have now fixed the padding issue, also I changed the str_replace to match your suggestion.
