### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by fluminis** [RobDWaller/ReallySimpleJWT#12]
Thanks for this cool project.

Some small possible improvements:
- You define a DateTime class _that provides and interface to the Carbon Date Time library_.
So use it everywhere and do not expose / use Carbon classes elsewhere.

- You split and decode the same token more than once when you validate it and get it's payload.
(The first time in _Token::validate_ and a second time in _Token::getPayload_)
Validate expiration decode the payload and json_decode it. You do it again in Token::getPayload

Have fun.

**Comment by RobDWaller** [comment]
Hi thanks for the feedback, I'm glad you like it. I have a few major changes to make for version 2 of this library, I will definitely add those updates to the mix as they make sense.

**Comment by RobDWaller** [comment]
These issues should be resolved by the release of version 2.0.0 so closing this ticket.
