### ISSUE TITLE
exp time in generated token should be an epoch number

### ISSUE THREAD

**Issue by dekatron** [RobDWaller/ReallySimpleJWT#13]
Hi,

I was trying to use this library to generate JWT tokens that could then be used to talk to another server running node (running express-jwt) however my tokens were getting rejected, after some digging I found that this library seemed to be generating the exp times as date strings rather than epoch numbers (even if you pass in an epoch number) I think this is because you are using a DateTime to parse the input and when you are outputting you're not using a formatter e.g. `->format('U')`

I was in a bit of a rush so I've used a different library but thought I would flag it up for you. Some relevant links below for anyone looking to make a fix. I haven't checked but I'd guess it's probably the same with any other dates e.g. iss

exp time should be a [NumericDate](https://tools.ietf.org/html/rfc7519#section-4.1.4), definition of a [NumericDate](https://tools.ietf.org/html/rfc7519#section-2)

**Comment by RobDWaller** [comment]
Thanks so much for this feedback. I'll look into this and see if I can fix it as soon as possible.

Cheers, Rob

**Comment by RobDWaller** [comment]
This should be fixed now, thanks for feeding back. Really helpful.
