### ISSUE TITLE
nesbot/carbon dependency conflicts with illuminate/support package

### ISSUE THREAD

**Issue by timothyfisherdev** [RobDWaller/ReallySimpleJWT#17]
Hi there!!

I read your blog post and am trying to implement your library in my current project. I'm using the illuminate/database component from Laravel, which installs the illuminate/support package, which requires nesbot/carbon "^1.24.1".

I'm getting the following output when attempting to require your package into my project:

    - Conclusion: don't install rbdwllr/reallysimplejwt 1.0.4
    - Conclusion: don't install rbdwllr/reallysimplejwt 1.0.3
    - Conclusion: don't install rbdwllr/reallysimplejwt 1.0.2
    - Conclusion: don't install rbdwllr/reallysimplejwt 1.0.1
    - Conclusion: remove nesbot/carbon 1.32.0
    - Installation request for rbdwllr/reallysimplejwt ^1.0 -> satisfiable by rbdwllr/reallysimplejwt[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4].
    - Conclusion: don't install nesbot/carbon 1.32.0
    - rbdwllr/reallysimplejwt 1.0.0 requires nesbot/carbon 1.22.* -> satisfiable by nesbot/carbon[1.22.0, 1.22.1].
    - Can only install one of: nesbot/carbon[1.22.0, 1.32.0].
    - Can only install one of: nesbot/carbon[1.22.1, 1.32.0].
    - Installation request for nesbot/carbon (locked at 1.32.0) -> satisfiable by nesbot/carbon[1.32.0].

I'm not too familiar with the workings of the carbon library, but was wondering if this could be resolved or not?

Thanks again and awesome package.

**Comment by RobDWaller** [comment]
Ok thanks for pointing this out. I'll fix this as soon as possible.

**Comment by RobDWaller** [comment]
This is fixed now, thanks for highlighting the issue.

**Comment by flyingwip** [comment]
Hi, 

I am trying to use your library as well and ran into the same sort of bug as @timothyfisherdev . 

I installed your package with composer require rbdwllr/reallysimplejwt .

  Problem 1
    - Conclusion: don't install rbdwllr/reallysimplejwt 1.0.4
    - Conclusion: don't install rbdwllr/reallysimplejwt 1.0.3
    - Conclusion: don't install rbdwllr/reallysimplejwt 1.0.2
    - Conclusion: don't install rbdwllr/reallysimplejwt 1.0.1
    - Conclusion: don't install rbdwllr/reallysimplejwt 1.0.0
    - Can only install one of: nesbot/carbon[1.32.0, 1.25.0].
    - Can only install one of: nesbot/carbon[1.32.0, 1.25.0].
    - Can only install one of: nesbot/carbon[1.32.0, 1.25.0].
    - rbdwllr/reallysimplejwt 1.0.5 requires nesbot/carbon 1.32.* -> satisfiable by nesbot/carbon[1.32.0].
    - Installation request for rbdwllr/reallysimplejwt ^1.0 -> satisfiable by rbdwllr/reallysimplejwt[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.
5].
    - Installation request for nesbot/carbon (locked at 1.25.0) -> satisfiable by nesbot/carbon[1.25.0].

Hope you can help me out.

**Comment by flyingwip** [comment]
Hi Rob,

The laravel version I installed is "laravel/framework": "5.6.*",

**Comment by RobDWaller** [comment]
Great, I'll do some testing this afternoon. Hopefully come up with an answer within next 24 hours.

**Comment by flyingwip** [comment]
Tanx for your quick response!

**Comment by RobDWaller** [comment]
@flyingwip I've made a fix and released version 1.0.6 which I'm hoping should help resolve the conflicts you've been experiencing.

I've tested with the libraries you've mentioned and cannot replicate the issue so hopefully it is resolved.

https://github.com/RobDWaller/ReallySimpleJWT/releases/tag/1.0.6

**Comment by flyingwip** [comment]
Cheers @RobDWaller . Composer has installed the package.

Thank you!

**Comment by RobDWaller** [comment]
Great, I'm going to close this issue again.

**Comment by bonzinho** [comment]
Hi, i have same error: Installation request for nesbot/carbon (locked at 2.18.0) -> satisfiable by nesbot/carbon[2.18.0].

Laravel 5.8

**Comment by RobDWaller** [comment]
You will not have this issue if you are using version 2.0.4 as Carbon was removed as a dependency in version 2.
