### ISSUE TITLE
Hash validation is susceptible to timing attacks

### ISSUE THREAD

**Issue by lcobucci** [RobDWaller/ReallySimpleJWT#2]
Due to [string comparison](https://github.com/RobDWaller/ReallySimpleJWT/blob/15d323fd02d2633654597acd8512fb774375cf3a/src/TokenValidator.php#L92), please use [`hash_equals()`](http://php.net/manual/en/function.hash-equals.php) instead.

**Comment by RobDWaller** [comment]
I hadn't even thought about Timing Attacks in this case, bit of a school boy, I'll fix.

**Comment by RobDWaller** [comment]
This should be resolved now. Thanks.
