### ISSUE TITLE
error: Uncaught Error: Class 'ReallySimpleJWT\TokenBuilder' not found

### ISSUE THREAD

**Issue by pars0097** [RobDWaller/ReallySimpleJWT#20]
just for test i created an index.php in scr folder
mycode:
```
<?php
include 'Token.php';
use ReallySimpleJWT\Token;

$token = Token::getToken('userIdentifier', 'secret', 'dateTimeString' | 'dateTimeNumber', 'issuerIdentifier');
```

full error message:
Fatal error: Uncaught Error: Class 'ReallySimpleJWT\TokenBuilder' not found in C:\wamp64\www\test\src\Token.php:77 Stack trace: #0 C:\wamp64\www\test\src\Token.php(28): ReallySimpleJWT\Token::builder() #1 C:\wamp64\www\test\src\index.php(5): ReallySimpleJWT\Token::getToken('userIdentifier', 'secret', 'dateTime_u\x7Fkow', 'issuerIdentifie...') #2 {main} thrown in C:\wamp64\www\test\src\Token.php on line 77

**Comment by RobDWaller** [comment]
Sorry for the slow response, been travelling with work. You should really use this library with composer and the composer auto-loader.

https://getcomposer.org/

Otherwise to get it working properly you'd need to include all the libraries files in your index.php file.

**Comment by RobDWaller** [comment]
As there is no further response to this issue I'm going to close it for now.
