### ISSUE TITLE
Suggestion: rename var $hash within TokenAbstract

### ISSUE THREAD

**Issue by stupkad** [RobDWaller/ReallySimpleJWT#27]
Hi,

first thanks for this great piece of work. I am looking for a jwt php library, as I am not really experienced with php. But as this is a very critical part I tried to understand the implementation.

I had a hard time to understand why a hash is fed to the signature and there used as algorithm - until I figured out it was just the name of the variable that kept me away from understanding the code. Perhaps it would make complex things easier to understand if a algorithm is named as such...

Merry Christmas, 
Dietmar

**Comment by RobDWaller** [comment]
This should be resolved by the release of version 2.0.0 so closing this ticket.
