### ISSUE TITLE
It Doesn't work

### ISSUE THREAD

**Issue by ismendoza** [RobDWaller/ReallySimpleJWT#28]
Nothing to explain I SPENT ONE SUNDAY IN THIS LIBRARY
ReallyDoesn'tWorkJWT

**Comment by RobDWaller** [comment]
Ok, well thank you for the feedback, but this isn't the most informative response to the library. The code is tested and people are using it so I'm relatively confident it works in most use cases.

Can you share with me the code you were trying to run and maybe I can look into this for you. It may be you have a unique use case I haven't considered before.

Also can I confirm you are using version 1.1.0? This is the last stable release of the code. 2.0.0 has not been released yet so is not defined as stable if you have been using that.

**Comment by RobDWaller** [comment]
I'm closing this because it's an utterly pointless comment with no reasonable feedback.
