### ISSUE TITLE
When/how to refresh the token

### ISSUE THREAD

**Issue by 0xboomie** [RobDWaller/ReallySimpleJWT#30]
Hi Rob,

We are currently implementing ReallySimpleJWT, but we have one question. When/how do we refresh the token? If we set an exp time of 3600 seconds, does the client need to contact the server for a new token, or does the server do this itself and send the new token whenever the client contacts the server?

The situation that made this question occur to me is like this: When the client needs to ask the server a new token every hour, but at the end of the day they shutdown their PC and go home. Do they need to log in that next morning, or will they contact the server with the old token and get an up-to-date one?

I hope I've made my question clear!

Kind regards :)

**Comment by larsverp** [comment]
+1

**Comment by RobDWaller** [comment]
There probably isn't a 'correct' answer to these questions. As there are numerous ways to implement JSON Web Tokens dependent on your use case.

As for the specific token renewal question. The user should submit a valid token, dependent on your rules. The server will then create a new token and send it back to the user. You will of course need a window for renewal. So if the token expires after 3600 seconds you should renew the token after 3000 seconds. Then you'll have a ten minute window of safety and the user should always have a valid token.

As for the more general login question. One approach may be to have two types of token. One for login which lasts 48 hours and is refreshed after 24 hours. And another type of token for requests which lasts for 10 minutes and is updated every few minutes.

This of course is just a suggestion, but I would advise you use https and you minimise the amount of PII (Personal Identifiable Information) stored in the token(s).

I hope this helps, and let me know if you have anymore questions.

**Comment by larsverp** [comment]
Okay! That makes everything a lot more clear for me. I do have one more question. What's the easiest way to test if a token is expired? Because I can just validate it, but then it's not specificaly testing if the time is still OK. So how do I only see if the time is OK?

**Comment by larsverp** [comment]
I'll ask a specific question. How do I see if a token is only valid for another 10 minutes or so, so I can tell when to refresh the token.

**Comment by larsverp** [comment]
I tried the getPayload method. And it workes great! Thanks a lot, this makes sense!

**Comment by RobDWaller** [comment]
Ok cool, glad I could help, I'm going to close this issue now.
