### ISSUE TITLE
PHP Version Required?

### ISSUE THREAD

**Issue by jazzyjeff5** [RobDWaller/ReallySimpleJWT#32]
I was having trouble with an error that the Token::customPayload function didn't exist, and tracked it down to the fact that composer had installed v1.1 of reallysimplejwt. When I tried forcing it to install version 2.0, I get:

Package rbdwllr/reallysimplejwt at version 2.0 has a PHP requirement incompatible with your PHP version (7.0.33)

So which PHP version is required? Thanks!

**Comment by RobDWaller** [comment]
Version 2.0 requires PHP 7.1 and above to run.

Version 1.0 requires PHP 7.0 and above, however the method you reference is not available in 1.0. You can read the documentation for version 1.0 here... https://github.com/RobDWaller/ReallySimpleJWT/blob/1.x/readme.md
