### ISSUE TITLE
Only Works With PHP 7.1

### ISSUE THREAD

**Issue by rcfrias** [RobDWaller/ReallySimpleJWT#36]
I am currently using php 7.0 on my prod server, and composer installs version 1.x which is not found by autoloader.

Locally I got the version 2.x and works great. only 7.0 has a bug in the autoloader.

**Comment by RobDWaller** [comment]
Hi,

Thanks for your message, this issue you are having is because we dropped support for PHP 7.0 after version 1.1. This is because PHP no longer supports PHP 7.0 https://www.php.net/supported-versions.php

Cheers, Rob
