### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by humpdaymedia** [RobDWaller/ReallySimpleJWT#40]
Would be useful to have instructions on how to install / incorporate into PHP web page.  I am an experienced programmer, but am admittedly new to PHP.  The documentation is skant on how to get it going.  A few sentences would go a long way to making what looks to be a great project - even better.  Any help on how to get it going on my PHP site?  What files are needed on the server?  How to incorporate into an existing PHP website? Thank you in advance for the help.

**Comment by RobDWaller** [comment]
I will look into this for you and try to make the documentation clearer. Thanks for the suggestion.

**Comment by RobDWaller** [comment]
I've added some additional documentation which I hope will help.
