### ISSUE TITLE
Audience validation?

### ISSUE THREAD

**Issue by tzkmx** [RobDWaller/ReallySimpleJWT#45]
Hi! I'm currently using your library in a refactoring of a legacy application around the Container of Laravel, rewriting all to get it into the full framework would be too costly. This library is currently helping me a lot to implement a sane authentication.

I'm just about to get into the authorization and I was thinking about using the audience claim, so I'd like to know if you have any plans or would be accepting PR to implement this as part of the library itself. Or don't and it should be something I could implement in a separate package.

Thanks for contributing this to the community and I look forward to a contribution if you are interested.

**Comment by RobDWaller** [comment]
Hi, sorry for the slow response, life issues, and thanks for the kind words.

To answer your question you can use the audience claim, it is available in the Build class and the Parsed class:

https://github.com/RobDWaller/ReallySimpleJWT/blob/master/src/Build.php#L191

https://github.com/RobDWaller/ReallySimpleJWT/blob/master/src/Parsed.php#L157

I hope this info helps. Let me know if you have any other questions.
