### ISSUE TITLE
Proposal: Add support for KID claim

### ISSUE THREAD

**Issue by dacgray** [RobDWaller/ReallySimpleJWT#46]
### Relevance

We need to use separate secrets depending on the service/client that requires auth.

This is difficult with the current setup since we need the key to get the header in `Token::getHeader()`

We, therefore, need to parse and get the kid claim from the header ourselves first - repeating logic and complicating things. 

### Proposal

Something like:

```php
<?php

declare(strict_types=1);

namespace ReallySimpleJWT;

/**
 * Value object for the generated JSON Web Token, takes the token and
 * the secret.
 *
 * @author Rob Waller <rdwaller1984@googlemail.com>
 */
class Jwt
{
    /**
     * The JSON Web Token string
     *
     * @var string $token
     */
    private $token;

    /**
    * The secret used to create the JWT signature
    *
    * @var string $secret
    */
    private $secret;

    /**
     * JWT Constructor
     *
     * @param string $token
     * @param string|array $secret Array to auto-determine secret from kid=>secret mapping
     */
    public function __construct(string $token, $secret)
    {
        $this->token = $token;

        if (is_string($secret)) {
            $this->secret = $secret;

            return;
        }

        $this->secret = $secret[$this->getKid()];
    }

    /**
     * Return the JSON Web Token String
     *
     * @return string
     */
    public function getToken(): string
    {
        return $this->token;
    }

    /**
     * Return the secret used to encode the JWT signature
     *
     * @return string
     */
    public function getSecret(): string
    {
        return $this->secret;
    }

    /**
     * @return string
     */
    private function getKid(): string
    {
        $header = substr(
            $this->token,
            0,
            strpos($this->token, '.')
        );

        $header = json_decode(base64_decode($header), true);

        return $header['kid'];
    }
}
```

**Comment by RobDWaller** [comment]
Sorry for the slow response here, I've been quite busy. 

I'm not quite sure I see the use case here sadly as the functionality should already be available. You can add any claim you wish to the header or payload within a token. 

```php
// See
ReallySimpleJWT\Build::setHeaderClaim(string $key, $value): self;

ReallySimpleJWT\Build::setPayloadClaim(string $key, $value): self;
```

The claims are then accessible once you parse the token.

```php
// See
ReallySimpleJWT\Parse::parse(): Parsed;

// And
ReallySimpleJWT\Parsed::getHeader(): array;

ReallySimpleJWT\Parsed::getPayload(): array;
```

I hope this information helps. Let me know if there are any other questions.

**Comment by dacgray** [comment]
The issue is that we need the key to parse, but when using kid we need to parse to get the key.

```php
$keyIdArray [
   'kid_A' => 'abc123!@#',
   'kid_B' => 'def456$%^',
]
```

---

we can only get the key if we know the key ID.
 🠕 🠗
we can only get the key ID if we know the key.

---

We need to do something like:

```php
$parsed = (new Parse(new Jwt('h.p.s', 'my-secret'), new Validate, new Encode))->parse();
```

We don't know `my-secret` because we don't know the key ID unless we parse.

So, we first manually need to parse the header to get the key ID.

```php
$parts = explode('.', $token);
    /**
     * @param string $token
     *
     * @return string|null
     */
    private static function getKid(string $token): ?string
    {
        $parts = explode('.', $token);

        return json_decode(base64_decode($parts[0]))->kid ?? null;
    }
```

The proposal is to native kid support to this package.

**Comment by RobDWaller** [comment]
Sorry I've been busy getting version 3.0.0 ready and missed your comment. Are you saying that you need to retrieve a claim from the header to then validate the signature? Or is it you need the key to decrypt the payload?

Apologies if you have moved on from this and solved this issue in another way, but your feedback would be useful.

**Comment by RobDWaller** [comment]
Also you don't need the secret to parse, you can just pass in an empty string, so long as you don't call the validate method the secret won't be used. So you can parse and then validate if necessary.

```php
$parse = new Parse(new Jwt('h.p.s', ''), new Validate, new Encode));
$parsed = $parse->parse();
$kid = $parsed->getHeader()['kid'];

// Lookup secret based on kid claim.

$parse = new Parse(new Jwt('h.p.s', 'my-secret'), new Validate, new Encode));
$parsed = $parse->validate()->parse();
```

**Comment by dacgray** [comment]
aah, nice - that solves it.

Perhaps think about adding a setter in 3.0 to `Jwt` to allow a bit more streamlining.

```php
        $jwt = new Jwt($token, '');
        $parse = new Parse(
            $jwt,
            new Validate,
            new Encode
        );
        $jwt->setSecret(
            $keys[$parse->parse()->getHeader()['kid']]
        );
        $parse->validate();
```
