### ISSUE TITLE
Why i can't use my own JWT secret?

### ISSUE THREAD

**Issue by rohitcoder** [RobDWaller/ReallySimpleJWT#54]
While using my own secret, i am getting this error

```
Fatal error: Uncaught ReallySimpleJWT\Exception\ValidateException: Invalid secret. in /Applications/MAMP/htdocs/xxxxxxx/assets/libs/vendor/rbdwllr/reallysimplejwt/src/Build.php:153
```

What is purpose of validating secret while building jWT? 
```php
if (!$this->secretValidator->validate($secret)) {
  throw new ValidateException('Invalid secret.', 9);
}
```

**Comment by rohitcoder** [comment]
It seems you are validating secret should contain alphanumeric and special chars but i want to use simple string

**Comment by rohitcoder** [comment]
I changed content of ``Secret.php``` 

#### From
```php
public function validate(string $secret): bool
    {
        if (
            !preg_match(
                '/^.*(?=.{12,}+)(?=.*[0-9]+)(?=.*[A-Z]+)(?=.*[a-z]+)(?=.*[\*&!@%\^#\$]+).*$/',
                $secret
            )
        ) {
            return false;
        }

        return true;
    }
```

#### To
```php
class Secret implements SecretInterface
{
    public function validate(string $secret): bool
    { 
        if(empty($secret)){
            return false;
        }
        return true;
    }
}
```

And now, its working let me know, if this could cause other problems in this lib (besides checking security of token by checking length/chars)

**Comment by rohitcoder** [comment]
Just a suggestion:

Add a feature to enable/disable this kind of restriction.

**Comment by RobDWaller** [comment]
@rohitcoder sorry for the slow response, the secret interface allows you to use your own secret as you've discovered. So long as you comply with the secret interface you won't have any problems.

https://github.com/RobDWaller/ReallySimpleJWT#custom-secrets

**Comment by markmorris** [comment]
Sorry to post on a closed topic, but this was the exact issue i was facing. You should remove the preg match or you cant use this library to authenticate Google API via JWT. Ive used many JWT libraries, Many node JS packages dont have this issue.

Used your fix @rohitcoder ty
