### ISSUE TITLE
Get payload without the token secret like on jwt.io?

### ISSUE THREAD

**Issue by h110m** [RobDWaller/ReallySimpleJWT#67]
Question should say everything.
Why do i have to insert the token secret when i just want for example my uid value from the payload.
I mean when i am posting my token inside https://jwt.io/#debugger-io i can also just access my values.

Edit: Just figured out you can also just pass an empty string into the getPayload function. But please update your code and the documentation to make this argument optional!

**Comment by RobDWaller** [comment]
Apologies for the slow response, thanks for the feedback and I will consider this in a future update.
