### ISSUE TITLE
Validate->notBefore should allow same sec timestamp

### ISSUE THREAD

**Issue by wire67** [RobDWaller/ReallySimpleJWT#69]
`notBefore` fails if the request is checked in the same timestamp it was generated: timestamp is 1000ms vs a HTTP request of few 10 to 100ms.
replace
`$notBefore < time()`
by 
`$notBefore <= time()`
in
`Validate.php`
this also does not allow for any clock drift between systems

**Comment by RobDWaller** [comment]
Hi, thanks for sharing this. I believe you are correct I will make this change.

**Comment by RobDWaller** [comment]
Closing this issue as the core problem should be solved in the latest release. https://github.com/RobDWaller/ReallySimpleJWT/releases/tag/4.0.3
